recently viewed products
peaksoft-school/gadgetarium pull request #75
Opened 2022-09-05 17:56 UTC by DilbaraAsanalieva

2022-09-05 18:26 UTC, beksultancs requested changes
Don't like logic from find recently viewed products

2022-09-13 05:50 UTC, UlanKubanychbekov commented on src/main/java/kg/gadgetarium/gadgetarium/db/model/Product.java
> +    @ManyToMany
OneToMany

2022-09-13 08:55 UTC, beksultancs commented on src/main/java/kg/gadgetarium/gadgetarium/db/model/Product.java
> +    @ManyToMany
berki jakty ManyToMany kylbaiby?

2022-09-13 12:28 UTC, UlanKubanychbekov commented on src/main/java/kg/gadgetarium/gadgetarium/db/model/Product.java
> +    @ManyToMany
бир юзердин несколько просмотренные товары болотта

2022-09-14 06:10 UTC, peaksoft-school commented on src/main/java/kg/gadgetarium/gadgetarium/apis/RecentlyViewedProductsApi.java
> +public class RecentlyViewedProductsApi {
Why this is a separate class for one endpoint?

2022-09-14 06:10 UTC, peaksoft-school commented on src/main/java/kg/gadgetarium/gadgetarium/apis/RecentlyViewedProductsApi.java
> +    public List<ProductRecentlyViewedResponse> getAllViews(@PathVariable Long userId){
We can add it to the Product API

2022-09-14 06:14 UTC, peaksoft-school commented on src/main/java/kg/gadgetarium/gadgetarium/db/service/RecentlyViewedProductsService.java
> +
Unnecessary lines from 61 to 76

2022-09-14 06:15 UTC, peaksoft-school reviewed
Commented 14.09.22 at 12 pm

2022-09-19 07:40 UTC, ChyngyzIshen commented on src/main/java/kg/gadgetarium/gadgetarium/apis/ProductApi.java
> +    @PreAuthorize("hasAnyAuthority('USER')")
Pls write in the next line

2022-09-19 07:41 UTC, ChyngyzIshen commented on src/main/java/kg/gadgetarium/gadgetarium/apis/ProductApi.java
> +    @Operation(summary = "read unread messages", description = "admin click on the button")
read, admin "r, a" should be capital

2022-09-19 07:42 UTC, ChyngyzIshen commented on src/main/java/kg/gadgetarium/gadgetarium/apis/ProductApi.java
> +    @PostMapping("viewed/{productId}")
Should be a post method?

2022-09-19 07:42 UTC, ChyngyzIshen commented on src/main/java/kg/gadgetarium/gadgetarium/db/model/ProductResponseStatus.java
> +    VIEWED,
Pls write in the next line

2022-09-19 07:42 UTC, ChyngyzIshen commented on src/main/java/kg/gadgetarium/gadgetarium/db/model/User.java
> +    public void deleteRecentlyViewed(Product product){
Pls write in the next line

2022-09-19 07:43 UTC, ChyngyzIshen commented on src/main/java/kg/gadgetarium/gadgetarium/db/model/User.java
> +    public void addRecentlyProduct(Product product){
Pls write in the next line

2022-09-19 07:43 UTC, ChyngyzIshen commented on src/main/java/kg/gadgetarium/gadgetarium/db/model/User.java
> +    public void deleteAllRecentlyViewed(List<Product> products){
Pls write in the next line

2022-09-19 07:43 UTC, ChyngyzIshen commented on src/main/java/kg/gadgetarium/gadgetarium/db/repositories/ProductRepository.java
> +    @Query("select p from Product p where(select u from User u where u.id=:userId) member of p.recentlyViewedUsers")
Pls write in the next line

2022-09-19 07:43 UTC, ChyngyzIshen reviewed
Commented 19.09.2022 at 1.40 pm

2022-09-22 09:27 UTC, merged